export const ACTIONS = {

  // CART
  MODIFY_PRODUCTS: "MODIFY_PRODUCTS",
  HANDLE_CUPON: "HANDLE_CUPON",

  // AUTH
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  RESET_ERROR: "RESET_ERROR",
  LOGOUT: "LOGOUT",

  // PRODUCT
  SET_PRODUCT: "SET_PRODUCT",
  SET_COLOR: "SET_COLOR",
  SET_COLORS: "SET_COLORS",
  SET_SIZE: "SET_SIZE",
  SET_SIZES: "SET_SIZES",
  SET_PRICES: "SET_PRICES",
  SET_EMPTY_PRODUCT: "SET_EMPTY_PRODUCT",
  SET_CONFIG: "SET_CONFIG",
  HANDLE_LIKE: "HANDLE_LIKE",
  LIKE_FALSE: "LIKE_FALSE",
  LIKE_TRUE: "LIKE_TRUE",

  // UI
  HANDLE_LOGIN: "OPEN_LOGIN",
  CLOSE_LOGIN: "CLOSE_LOGIN",
  HANDLE_MENU: "HANDLE_MENU",
  CLOSE_MENU: "CLOSE_MENU",
  HANDLE_CART: "HANDLE_CART",
  CLOSE_CART: "CLOSE_CART",
  HANDLE_SEARCH: "HANDLE_SEARCH",
  CLOSE_SEARCH: "CLOSE_SEARCH",
  HANDLE_CUPON_UI: "HANDLE_CUPON",
  CLOSE_CUPON: "CLOSE_CUPON"

}